---
- hosts: "app:mongo"
  become: yes
  tags:
    - dependencies
  tasks:
    - name: Upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Register reboot required file
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if Required
      reboot:
      when: reboot_required.stat.exists

- hosts: app
  become: yes
  tags:
    - dependencies
    - python
  tasks:
    - name: Install python deployment dependencies
      ansible.builtin.apt:
        name:
          - jq
          - python3-pip
          - python3-venv
          - python3-virtualenv
          - python3-boto3
          - python3-botocore
        state: present

- hosts: app
  become: yes
  tags:
    - dependencies
  tasks:
    - name: Check for built htslib
      ansible.builtin.stat:
        path: "/usr/local/bin/htslib"
      register: hts_stat

    - name: Build htslib
      ansible.builtin.include_role:
        name: htslib
      when: not hts_stat.stat.exists

- hosts: mongo
  become: yes
  tags:
    - dependencies
  tasks:
    - name: Unzip and jq
      ansible.builtin.apt:
        name:
          - unzip
          - jq
        state: present

    - name: Download aws cli installer
      ansible.builtin.unarchive:
        src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ansible_architecture}}.zip"
        dest: "/tmp"
        remote_src: true
        creates: "/tmp/aws"
        mode: 0755

    - name: Install awscli
      ansible.builtin.command:
        cmd: /tmp/aws/install
        creates: /usr/local/bin/aws

# Mount EBS volume holding the Application & Data
- hosts: "app:mongo"
  tags:
    - setup
  tasks:
    - name: Set default value for filesystem type of data volume
      ansible.builtin.set_fact:
        fs_type: xfs
      when: fs_type is undefined

    - name: Copy EBS device name resolution script
      become: yes
      ansible.builtin.template:
        mode: 0755
        dest: /usr/local/bin/gen_ebs_mount_env.sh
        src: templates/gen_ebs_mount_env.sh.j2

    - name: Copy systemd name resolution service
      become: yes
      ansible.builtin.template:
        mode: 0555
        dest: /etc/systemd/system/bravo-ebs-discovery.service
        src: templates/bravo-ebs-discovery.service.j2

    - name: Copy bravo systemd mount file
      become: yes
      ansible.builtin.template:
        mode: 0555
        dest: /etc/systemd/system/bravo.mount
        src: templates/bravo.mount.j2

    - name: Resolve EBS block device name
      ansible.builtin.command: "/usr/local/bin/gen_ebs_mount_env.sh '/dev/null'"
      register: blk_device_result

    - name: Create base directory of mount point
      become: yes
      ansible.builtin.file:
        path: "{{base_dir}}"
        state: directory

    - name: Query block device format 
      ansible.builtin.command: "lsblk --noheadings --output FSTYPE {{blk_device_result.stdout}}"
      register: blk_fstype

    # Format volume when it does not match the expected type.
    - name: Format ebs data filesystem
      become: yes
      community.general.filesystem:
        dev: "{{blk_device_result.stdout}}"
        fstype: "{{fs_type}}"
        force: yes
      when: blk_fstype.stdout_lines[0] != fs_type

    - name: Reload systemd daemon to pick up ebs mounting services
      become: yes
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Start EBS device name discovery service
      become: yes
      ansible.builtin.systemd_service:
        name: "bravo-ebs-discovery.service"
        enabled: true
        state: "started"

    - name: Start EBS mount
      become: yes
      ansible.builtin.systemd_service:
        name: "bravo.mount"
        enabled: true
        state: "started"

    - name: Start EBS mount
      become: yes
      ansible.builtin.systemd_service:
        name: "bravo.mount"
        enabled: true
        state: "started"

    # - name: Mount ebs data filesystem
    #   become: yes
    #   ansible.posix.mount:
    #     src: /dev/nvme1n1
    #     path: "{{base_dir}}"
    #     fstype: "{{fs_type}}"
    #     state: mounted

    - name: Update owner of mounted directory
      become: yes
      ansible.builtin.file:
        path: "{{base_dir}}"
        state: directory
        owner: "{{ansible_user_id}}"
        group: "{{ansible_user_id}}"



- hosts: app
  become: no
  tags:
    - instance
  vars:
    mongo_host: "{{ groups['mongo'] | first }}"
    mongo_ip: "{{ hostvars[mongo_host]['private_ip'] }}"
    bravo_ref: "main"
  tasks:
    - name: Create API instance dir
      become: yes
      ansible.builtin.file:
        path: "{{inst_dir}}/api"
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Build S3 enabled pysam in virtual environment
      ansible.builtin.pip:
        name: 
          - pysam
        virtualenv: "/home/ubuntu/bravo_venv"
        state: present
        extra_args: "--no-binary pysam"
      environment:
        HTSLIB_CONFIGURE_OPTIONS: "--enable-libcurl --enable-s3"

    # Remove legacy dir structure from instance dir to allow symlinking
    - name: Stat bravo venv
      ansible.builtin.stat:
        path: "{{inst_dir}}/api/venv"
      register: venv_status

    - name: Remove venv directory in instance directory
      ansible.builtin.file:
        path: "{{inst_dir}}/api/venv"
        state: absent
      when: venv_status.stat.exists and venv_status.stat.isdir

    - name: Create symlink to venv from instance directory
      ansible.builtin.file:
        path: "{{inst_dir}}/api/venv"
        state: link
        src: "/home/ubuntu/bravo_venv"
        owner: ubuntu
        group: ubuntu

    - name: Install Bravo API and dependencies into API venv
      ansible.builtin.pip:
        name:
          - "git+https://github.com/statgen/bravo_api.git@{{bravo_ref}}"
          - gunicorn
          - gevent
        virtualenv: "/home/ubuntu/bravo_venv"
        state: present
        extra_args: "--upgrade"

    - name: Create API config
      ansible.builtin.template:
        mode: 0775
        dest: "{{inst_dir}}/api/config.py"
        src: templates/config_api.py.j2

- hosts: app
  become: yes
  tags:
    - instance
    - systemd
  # From https://www.jeffgeerling.com/blog/2017/quick-way-check-if-youre-aws-ansible-playbook
  tasks:
    - name: Get Token for EC2 metadata service V2
      uri:
        url: "http://169.254.169.254/latest/api/token"
        method: PUT
        headers:
          X-aws-ec2-metadata-token-ttl-seconds: 60
        return_content: true
      register: token_resp
      failed_when: False

    - name: Check if running in AWS by is ec2 metadata available.
      uri:
        url: http://169.254.169.254/latest/meta-data
        timeout: 2
        headers:
          X-aws-ec2-metadata-token: "{{token_resp.content}}"
      register: aws_uri_check
      failed_when: False

    - set_fact:
        is_aws_environment: "{{ aws_uri_check.status == 200 }}"

    - name: Remove legacy credentials file
      ansible.builtin.file:
        path: "{{inst_dir}}/credentials"
        state: absent

    - name: Script for HTSLIB S3 credentials
      ansible.builtin.template:
        mode: 0755
        dest: /usr/local/sbin/hts_credentials.sh
        src: templates/hts_credentials.sh.j2
      when: is_aws_environment

    - name: Systemd service for HTSLIB S3 credentials
      ansible.builtin.template:
        mode: 0755
        dest: /etc/systemd/system/hts-credentials.service
        src: templates/hts-credentials.service.j2
      when: is_aws_environment

    - name: Start credentials service
      ansible.builtin.systemd:
        daemon_reload: yes
        name: hts-credentials.service
        enabled: yes
        state: restarted
      when: is_aws_environment

    - name: Systemd service for API
      ansible.builtin.template:
        mode: 0755
        dest: /etc/systemd/system/bravo-api.service
        src: templates/bravo-api.service.j2

    - name: Reload systemd daemons
      ansible.builtin.systemd:
        name: bravo-api.service
        state: restarted

- hosts: mongo
  become: yes
  tags:
    - database
    - dependencies
  roles:
    - role: community.mongodb.mongodb_repository
      vars:
        mongodb_version: "7.0"
    - role: community.mongodb.mongodb_install


- hosts: mongo
  become: yes
  tags:
    - database
    - dependencies
  tasks:
    - name: Alter group owner of base_dir
      ansible.builtin.file:
        path: "{{base_dir}}"
        state: directory
        group: mongodb
        mode: "0775"

    - name: Create mongo db directory
      ansible.builtin.file:
        path: "{{base_dir}}/mongodata"
        state: directory
        group: mongodb
        owner: mongodb
    - name: Change mongo db data directory config
      ansible.builtin.lineinfile:
        path: /etc/mongod.conf
        search_string: "  dbPath: /var/lib/mongodb"
        line: "  dbPath: {{base_dir}}/mongodata"
        state: present
    - name: Change mongo db ip binding
      ansible.builtin.lineinfile:
        path: /etc/mongod.conf
        search_string: "  bindIp: 127.0.0.1"
        line: "  bindIp: 0.0.0.0"
        state: present

- hosts: mongo
  become: yes
  tags:
    - database
    - dependencies
  tasks:
    - name: Restart mongod service
      ansible.builtin.systemd:
        name: mongod.service
        state: restarted
        enabled: true

- hosts: app
  tags:
    - data
  tasks:
    - name: Download core runtime data and load basis data into mongo
      ansible.builtin.include_role:
        name: core_data
      when: load_data

    - name: Create runtime reference directory
      ansible.builtin.file:
        path: "{{base_dir}}/data/runtime/reference"
        state: "directory"

    - name: Download runtime reference fasta from S3
      amazon.aws.s3_object:
        bucket: "{{data_bucket}}"
        object: "runtime/reference/{{item}}"
        mode: "get"
        overwrite: "latest"
        dest: "{{base_dir}}/data/runtime/reference/{{item}}"
      loop:
        - "hs38DH.fa"
        - "hs38DH.fa.fai"
      when: data_bucket | length > 0

- hosts: mongo
  tags:
    - data
    - eqtl
  tasks:
    - name: Load and integrate eqtl data
      ansible.builtin.include_role:
        name: eqtl_data
      when: load_data

- hosts: app
  become: yes
  gather_facts: no
  tags:
    - systemd
    - start
  tasks:
    - name: Start API service
      ansible.builtin.systemd:
        daemon_reload: yes
        name: bravo-api.service
        enabled: yes
        state: reloaded

- hosts: "app"
  become: yes
  tags:
    - security
  vars:
    tenable_source_name: "{{inventory_hostname}}"
  tasks:
    - name: Install Tenable agent
      ansible.builtin.include_role:
        name: tenable
      when: tenable_key is defined

