---
# This download all task assumes the structure under the key in the data bucket
# matches the runtime expectations of the BRAVO API application.
- name: Enumerate keys in bucket.
  amazon.aws.s3_object:
    bucket: "{{data_bucket}}"
    prefix: "{{data_key}}"
    mode: list
  register: s3list

- name: Convenience list of paths relative to data_key
  ansible.builtin.set_fact:
    rel_paths: "{{ s3list.s3_keys | map('replace', data_key + '/', '', 1) }}"
  when: data_key | length > 0

- name: Convenience list of paths relative bucket root
  vars:
    cram_regex: '\.cram'
  ansible.builtin.set_fact:
    rel_paths: "{{ s3list.s3_keys | reject('regex', cram_regex) }}"
  when: data_key | length == 0

- name: Create data subdirectories
  ansible.builtin.file:
    path: "{{ (data_dir, item) | path_join}}"
    state: directory
  loop: "{{rel_paths | map('dirname') | unique}}"

- name: Get files from bucket.
  amazon.aws.s3_object:
    bucket: "{{data_bucket}}"
    object: "{{data_key}}/{{item}}"
    dest:   "{{(data_dir, item) | path_join}}"
    mode: get
    overwrite: never
  loop: "{{rel_paths}}"

- name: Make data directory readable
  ansible.builtin.file:
    path: "{{data_dir}}"
    mode: "0775"
    recurse: true
